name: lint-and-test-workflow

on:
  push:
    branches:
      - master

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: "3.9"

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pylint
        run: pylint modules

      - name: Core Unit Test
        run: pytest core
      - name: Module Interface Test
        run: pytest modules/test_module_interfaces.py
      - name: Module Unit Tests
        run: pytest --ignore=modules/test_module_interfaces.py modules
