name: lint-and-test-workflow

on:
  push:
    branches:
      - master

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: "3.9"

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint core
        run: pylint autosec/core
      - name: Lint modules
        run: pylint autosec/modules

      - name: Core Tests
        run: pytest autosec/core
      - name: Module Interface Test
        run: pytest autosec/modules/test_module_interfaces.py
      - name: Module Tests
        run: pytest --ignore=autosec/modules/test_module_interfaces.py autosec/modules
